### ISSUE TITLE
CookieBro does not seem to block all cookies

### ISSUE THREAD

**Issue by SiL3NC3** [smikodanic/cookie-bro#1]
The manual says:

![image](https://github.com/smikodanic/cookie-bro/assets/694970/068b0f6a-39de-4e26-9919-32a8691ce780)

It seems, that when I activate blacklist filtering, and giving `*.*`, that it does not have any effect.
How can ALL cookies be blocked by default properly?

**Comment by SiL3NC3** [comment]
closed - was related to the chrome extension

**Comment by smikodanic** [comment]
:+1:
